apiVersion: v1
kind: Secret
metadata:
  name: user-token
  namespace: user-space
  annotations:
    kubernetes.io/service-account.name: user
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: developer-token
  namespace: dev
  annotations:
    kubernetes.io/service-account.name: developer
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: devops-token
  namespace: default
  annotations:
    kubernetes.io/service-account.name: devops
type: kubernetes.io/service-account-token